name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['7.3', '8.0']

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl
                  coverage: pcov

            - name: Checkout
              uses: actions/checkout@v2

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: |
                  composer --version
                  composer install --optimize-autoloader

            - name: Codecept run
              run: vendor/bin/codecept run --coverage-xml

            - name: ReportGenerator
              uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
              with:
                  reports: './tests/_output/coverage.xml'
                  targetdir: './coverage'
                  reporttypes: 'lcov'

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  path-to-lcov: './tests/_output/coverage.xml'
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Code Coverage Report
              if: success() && matrix.php-version == '7.3'
              uses: codecov/codecov-action@v1
              with:
                file: ./tests/_output/coverage.xml

    checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['7.3', '8.0']

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl

            - name: Checkout
              uses: actions/checkout@v2

            - name: Composer validate
              run: composer validate

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: |
                  composer --version
                  composer install --optimize-autoloader

            - name: PHPStan checks
              run: composer stan

            - name: CodeStyle checks
              run: composer cs-check
